/**
 * DOM Event Map Interface
 * 
 * Auto-generated from TypeScript's lib.dom.d.ts
 * DO NOT EDIT - This file is generated by scripts/generate.ts
 */

/**
		 * Comprehensive DOM Event Map Interface
		 *
		 * This interface extends all DOM-relevant EventMap interfaces from TypeScript's lib.dom.d.ts:
		 *  * - DocumentEventMap
 * - ElementEventMap
 * - GlobalEventHandlersEventMap
 * - HTMLBodyElementEventMap
 * - HTMLElementEventMap
 * - HTMLFrameSetElementEventMap
 * - HTMLMediaElementEventMap
 * - HTMLVideoElementEventMap
 * - MathMLElementEventMap
 * - SVGElementEventMap
 * - SVGSVGElementEventMap
 * - ShadowRootEventMap
 * - WindowEventHandlersEventMap
 * - WindowEventMap
		 *
		 * Provides typed events with proper Event subtypes (MouseEvent, KeyboardEvent, etc.)
		 * by leveraging TypeScript's interface inheritance rather than merging properties.
		 *
		 * Usage in any JSX framework:
		 *
		 * ```typescript
		 * import { DOMEventMap } from './jsx-dom-types.js';
		 *
		 * // For frameworks with addEventListener support:
		 * declare global {
		 *	 module YourFramework {
		 *		 interface EventMap extends DOMEventMap {}
		 *	 }
		 * }
		 * ```
		 */
		export interface DOMEventMap extends DocumentEventMap, ElementEventMap, GlobalEventHandlersEventMap, HTMLBodyElementEventMap, HTMLElementEventMap, HTMLFrameSetElementEventMap, HTMLMediaElementEventMap, HTMLVideoElementEventMap, MathMLElementEventMap, SVGElementEventMap, SVGSVGElementEventMap, ShadowRootEventMap, WindowEventHandlersEventMap, WindowEventMap {}
