/**
 * Generate the camelCase prop-name variant from React's own
 * `possibleStandardNames.js` (pinned to a release). React/Inferno and other
 * frameworks that camelCase JSX props (`class` → `className`, `tabindex` →
 * `tabIndex`, …) can apply this variant; the standard types stay native.
 *
 * The whole thing is emitted as one generated `.d.ts` — the name map plus the
 * tiny re-keying type — so there's a single file to consume and nothing
 * hand-maintained.
 */

const REACT_VERSION = "v19.2.7";
const SOURCE_URL = `https://raw.githubusercontent.com/facebook/react/${REACT_VERSION}/packages/react-dom-bindings/src/shared/possibleStandardNames.js`;

const response = await fetch(SOURCE_URL);
if (!response.ok) {
	throw new Error(`Failed to fetch ${SOURCE_URL}: ${response.status}`);
}

const source = await response.text();

// Each entry is `name: 'camelCaseName',` — the key is optionally quoted (for
// names with `:` or `-`), the value is always single-quoted.
const ENTRY = /^\s*('?)([\w:-]+)\1:\s*'([\w:-]+)',/gm;
const names: Record<string, string> = {};
let match: RegExpExecArray | null;
while ((match = ENTRY.exec(source))) {
	const [, , attribute, camelName] = match;
	names[attribute] = camelName;
}

if (Object.keys(names).length === 0) {
	throw new Error("Parsed zero entries from possibleStandardNames.js");
}

const entries = Object.keys(names)
	.sort()
	.map((attr) => `\t${JSON.stringify(attr)}: ${JSON.stringify(names[attr])};`)
	.join("\n");

const dts = `// AUTO-GENERATED — DO NOT EDIT.
// Generated by scripts/parse-camel-case-names.ts from React ${REACT_VERSION}'s
// possibleStandardNames.js — the canonical camelCase JSX prop-name list.
// ${SOURCE_URL}

import type {WebIntrinsicElements} from "./jsx-web";

/** Web-platform attribute name → camelCase JSX prop name (\`class\` → \`className\`). */
interface CamelCaseNames {
${entries}
}

// Re-key an element's props: a name in the map takes its camelCase name; any
// other name is kept as-is.
type CamelCase<TProps> = {
	[K in keyof TProps as K extends keyof CamelCaseNames
		? CamelCaseNames[K] extends string
			? CamelCaseNames[K]
			: K
		: K]: TProps[K];
};

/**
 * Every web-platform element with camelCase JSX prop names applied
 * (\`className\`, \`htmlFor\`, \`tabIndex\`, …). For React, Inferno, and other
 * frameworks that use React's prop-naming convention. Supply the framework's
 * reserved props (\`key\`/\`ref\`/…) via the first type parameter, exactly like
 * the standard \`WebIntrinsicElements\`.
 */
export type CamelCaseIntrinsicElements<
	TIntrinsicAttributes = {},
	TElementChildrenAttribute = {children?: unknown},
	TPropOverrides = {},
> = {
	[Tag in keyof WebIntrinsicElements<
		TIntrinsicAttributes,
		TElementChildrenAttribute,
		TPropOverrides
	>]: CamelCase<
		WebIntrinsicElements<
			TIntrinsicAttributes,
			TElementChildrenAttribute,
			TPropOverrides
		>[Tag]
	>;
};
`;

await Bun.write("./src/camel-case.generated.d.ts", dts);
console.log(
	`💾 Generated camel-case.generated.d.ts from ${Object.keys(names).length} React prop-name mappings`,
);
