// React SVG camelCase → standard SVG attribute mapping.
// Only includes entries where the React name differs from the SVG attribute name.
// Source: packages/eslint-plugin-crank/src/rules/no-react-svg-props.ts
export const REACT_SVG_PROPS: Record<string, string> = {
	// Presentation attributes
	clipPath: "clip-path",
	clipRule: "clip-rule",
	colorInterpolation: "color-interpolation",
	colorInterpolationFilters: "color-interpolation-filters",
	colorRendering: "color-rendering",
	dominantBaseline: "dominant-baseline",
	fillOpacity: "fill-opacity",
	fillRule: "fill-rule",
	floodColor: "flood-color",
	floodOpacity: "flood-opacity",
	fontFamily: "font-family",
	fontSize: "font-size",
	fontStretch: "font-stretch",
	fontStyle: "font-style",
	fontVariant: "font-variant",
	fontWeight: "font-weight",
	glyphOrientationHorizontal: "glyph-orientation-horizontal",
	glyphOrientationVertical: "glyph-orientation-vertical",
	imageRendering: "image-rendering",
	letterSpacing: "letter-spacing",
	lightingColor: "lighting-color",
	markerEnd: "marker-end",
	markerMid: "marker-mid",
	markerStart: "marker-start",
	overlinePosition: "overline-position",
	overlineThickness: "overline-thickness",
	paintOrder: "paint-order",
	pointerEvents: "pointer-events",
	shapeRendering: "shape-rendering",
	stopColor: "stop-color",
	stopOpacity: "stop-opacity",
	strikethroughPosition: "strikethrough-position",
	strikethroughThickness: "strikethrough-thickness",
	strokeDasharray: "stroke-dasharray",
	strokeDashoffset: "stroke-dashoffset",
	strokeLinecap: "stroke-linecap",
	strokeLinejoin: "stroke-linejoin",
	strokeMiterlimit: "stroke-miterlimit",
	strokeOpacity: "stroke-opacity",
	strokeWidth: "stroke-width",
	textAnchor: "text-anchor",
	textDecoration: "text-decoration",
	textRendering: "text-rendering",
	underlinePosition: "underline-position",
	underlineThickness: "underline-thickness",
	vectorEffect: "vector-effect",
	wordSpacing: "word-spacing",
	writingMode: "writing-mode",
	// Other
	alignmentBaseline: "alignment-baseline",
	baselineShift: "baseline-shift",
	enableBackground: "enable-background",
	// xlink/xml namespace attributes (deprecated in SVG 2 but still used)
	xlinkActuate: "xlink:actuate",
	xlinkArcrole: "xlink:arcrole",
	xlinkHref: "xlink:href",
	xlinkRole: "xlink:role",
	xlinkShow: "xlink:show",
	xlinkTitle: "xlink:title",
	xlinkType: "xlink:type",
	xmlBase: "xml:base",
	xmlLang: "xml:lang",
	xmlSpace: "xml:space",
};
